language: ruby
cache: bundler
gemfile:
  - Gemfile-rails.4.0.x
  - Gemfile-rails.4.1.x
  - Gemfile-rails.4.2.x
  - Gemfile-rails.5.0.x
  - Gemfile-rails.5.1.x
  - Gemfile-rails.5.2.x
  - Gemfile-rails.6.0.x
  - Gemfile
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - jruby
matrix:
  exclude:
    - rvm: 2.4
      gemfile: Gemfile-rails.4.0.x
    - rvm: 2.5
      gemfile: Gemfile-rails.4.0.x
    - rvm: 2.6
      gemfile: Gemfile-rails.4.0.x
    - rvm: 2.7
      gemfile: Gemfile-rails.4.0.x
    - rvm: 2.4
      gemfile: Gemfile-rails.4.1.x
    - rvm: 2.5
      gemfile: Gemfile-rails.4.1.x
    - rvm: 2.7
      gemfile: Gemfile-rails.4.1.x
    - rvm: 2.6
      gemfile: Gemfile-rails.4.1.x
    - rvm: 2.6
      gemfile: Gemfile-rails.4.2.x
    - rvm: 2.7
      gemfile: Gemfile-rails.4.2.x
    - rvm: 2.7
      gemfile: Gemfile-rails.5.0.x
    - rvm: 2.7
      gemfile: Gemfile-rails.5.1.x
    - rvm: 2.2
      gemfile: Gemfile-rails.6.0.x
    - rvm: 2.3
      gemfile: Gemfile-rails.6.0.x
    - rvm: 2.4
      gemfile: Gemfile-rails.6.0.x
    - rvm: 2.2
      gemfile: Gemfile
    - rvm: 2.3
      gemfile: Gemfile
    - rvm: 2.4
      gemfile: Gemfile
    - rvm: jruby
      gemfile: Gemfile-rails.5.0.x
    - rvm: jruby
      gemfile: Gemfile-rails.5.1.x
    - rvm: jruby
      gemfile: Gemfile-rails.5.2.x
    - rvm: jruby
      gemfile: Gemfile-rails.6.0.x
    - rvm: jruby
      gemfile: Gemfile
  allow_failures:
    - rvm: jruby
