gemfile:
  - Gemfile-rails.3.2.x
  - Gemfile-rails.4.0.x
  - Gemfile-rails.4.1.x
  - Gemfile
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - jruby
matrix:
  exclude:
    - rvm: 2.2
      gemfile: Gemfile-rails.3.2.x
