language: ruby
cache: bundler
sudo: false
gemfile:
  - Gemfile-rails.3.2.x
  - Gemfile-rails.4.0.x
  - Gemfile-rails.4.1.x
  - Gemfile-rails.5.x
  - Gemfile
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.9
  - 2.2.5
  - 2.3.1
  - jruby
matrix:
  exclude:
    - rvm: 2.2.5
      gemfile: Gemfile-rails.3.2.x
    - rvm: 1.9.3
      gemfile: Gemfile-rails.5.x
    - rvm: 1.9.3
      gemfile: Gemfile
    - rvm: 2.0.0
      gemfile: Gemfile-rails.5.x
    - rvm: 2.0.0
      gemfile: Gemfile
    - rvm: 2.1.9
      gemfile: Gemfile-rails.5.x
    - rvm: 2.1.9
      gemfile: Gemfile
    - rvm: jruby
      gemfile: Gemfile-rails.5.x
    - rvm: jruby
      gemfile: Gemfile
